### ISSUE TITLE
! LaTeX Error: File `dsfont.sty' not found.

### ISSUE THREAD

**Issue by synctext** [vandenheuvel/mathematics-of-trust#1]
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))

! LaTeX Error: File `dsfont.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:

**Comment by vandenheuvel** [comment]
This is a missing font package which can be installed from the repositories from all major distributions. Closing.

**Comment by nefur** [comment]
dsfont is a font belongs to the package "doublestroke" you can use "tlmgr install doublestroke"command to install it
